version: '3.8'

services:
  db:
    image: postgres:16.1
    container_name: shareit-postgres
    environment:
      POSTGRES_DB: shareitdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: e0gD0os9
      POSTGRES_HOST_AUTH_METHOD: trust
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d shareitdb"]
      interval: 5s
      timeout: 5s
      retries: 30
      start_period: 30s
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - shareit-network

  shareit-server:
    build:
      context: ./shareit-server
      dockerfile: Dockerfile
    container_name: shareit-server
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SERVER_PORT: 9090
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/shareitdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: e0gD0os9
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_DATASOURCE_HIKARI_CONNECTION_TIMEOUT: 60000
      SPRING_DATASOURCE_HIKARI_INITIALIZATION_FAIL_TIMEOUT: 60000
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9090/actuator/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 20
      start_period: 60s
    ports:
      - "9090:9090"
    networks:
      - shareit-network
    restart: on-failure

  shareit-gateway:
    build:
      context: ./shareit-gateway
      dockerfile: Dockerfile
    container_name: shareit-gateway
    environment:
      SHAREIT_SERVER_URL: http://shareit-server:9090
    depends_on:
      shareit-server:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/actuator/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 15
    ports:
      - "8080:8080"
    networks:
      - shareit-network
    restart: on-failure

volumes:
  postgres_data: