version: '3.8'

services:
  shareit-gateway:
    build: ./shareit-gateway
    ports:
      - "8080:8080"
    depends_on:
      - shareit-server
    environment:
      - SHAREIT_SERVER_URL=http://shareit-server:9090

  shareit-server:
    build: ./shareit-server
    ports:
      - "9090:9090"
    environment:
      - SPRING_PROFILES_ACTIVE=default
      - SERVER_PORT=9090
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/shareitdb
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=e0gD0os9
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.PostgreSQLDialect
      - SPRING_AUTOCONFIGURE_EXCLUDE=org.springframework.boot.autoconfigure.h2.H2ConsoleAutoConfiguration
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:16.1
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=shareitdb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=e0gD0os9
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d shareitdb"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: